"""
Django settings for EraAdmin project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.conf.global_settings import SESSION_COOKIE_NAME, SESSION_COOKIE_PATH

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-((7ym5scgwecr@5re8r^sp9nq!pkq4unn6s&nq$1*xc&twlsaw'

SAFE_SALT = '8vrC#BedKqh9a*Np'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'localhost:8080', 'http://localhost:8080']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'corsheaders',
    'oauth2_provider',
    'EraAdmin',
    'apps.books',
]

AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend'
]

MIDDLEWARE_CLASSES = [
    'oauth2_provider.middleware.OAuth2TokenMiddleware'
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'EraAdmin.middleware.exception.ExceptionMiddleware',
    'EraAdmin.middleware.http.HttpMiddleware',
    'EraAdmin.middleware.auth.AuthMiddleware',
    'EraAdmin.middleware.format.FormatMiddleware'
]

ROOT_URLCONF = 'EraAdmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EraAdmin.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASE_ROUTERS = ['EraAdmin.app.DatabaseAppsRouter']
DATABASES = {
    'sqlite3': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'era',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'POST': 3306,
    },
    'books': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'books',
        'USER': 'books_admin',
        'PASSWORD': 'books_admin',
        'HOST': '127.0.0.1',
        'POST': 3306,
    }
}
DATABASE_APPS_MAPPING = {
    'books': 'books',
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 10, "decode_responses": True},
        }
    }
}

# session
SESSION_ENGINE = "django.contrib.sessions.backends.file"

# 字母验证码
CAPTCHA_IMAGE_SIZE = (100, 38)
CAPTCHA_LENGTH = 5
CAPTCHA_TIMEOUT = 1

# 允许所有域名跨域(优先选择)
# CORS_ORIGIN_ALLOW_ALL = True
# 或配置白名单
CORS_ORIGIN_WHITELIST = (
    'http://localhost:8080',
    'http://127.0.0.1:8080'
    # '127.0.0.1:8000',
    # 'localhost:8000',
    # '127.0.0.1:8080',
    # 'localhost:8080',
    # 'ads-cms-api.aataotao.com:8000'  #
    # 'taoduoduo-test.oss-cn-shenzhen.aliyuncs.com:80',  # 线上
    # '10.0.2.187:8080'  # 本地
)
CORS_ALLOW_CREDENTIALS = True
# 前端需要携带cookies访问后端时,需要设置withCredentials: true


CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'dnt',
    'origin',
    'authorization',
    'x-csrftoken',
    'accept-encoding',
    'user-agent',
    'cookie'
)

SESSION_COOKIE_HTTPONLY = False

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
